import { createGlspModule, createGlspSharedModule } from 'glsp-langium-integration/langium';
import { inject, type Module } from 'langium';
import { type DefaultSharedModuleContext, type LangiumServices, type PartialLangiumServices } from 'langium/lsp';
import { ConditionalEdgeDSLGeneratedModule, WorkflowDslGeneratedSharedModule } from './generated/module.js';
import { WorkflowDslScopeComputation, WorkflowDslScopeProvider, WorkflowExternalNodeInformationService } from './workflow-dsl-references.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type WorkflowDslAddedServices = {};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type WorkflowDslServices = LangiumServices & WorkflowDslAddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const WorkflowDslModule: Module<WorkflowDslServices, PartialLangiumServices & WorkflowDslAddedServices> = {
    references: {
        ScopeComputation: services => new WorkflowDslScopeComputation(services),
        ScopeProvider: services => new WorkflowDslScopeProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services (extended with the GLSP integration services)
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services (extended with the GLSP integration services)
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createWorkflowDslServices(context: DefaultSharedModuleContext) {
    const shared = inject(
        createGlspSharedModule(context, {
            ExternalNodeInformationService: services => new WorkflowExternalNodeInformationService(services)
        }),
        WorkflowDslGeneratedSharedModule
    );

    const ConditionalEdgeDSL = inject(createGlspModule({ shared }), ConditionalEdgeDSLGeneratedModule, WorkflowDslModule);

    shared.ServiceRegistry.register(ConditionalEdgeDSL);

    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, ConditionalEdgeDSL };
}
