import { inject, type Module } from 'langium';
import { type DefaultSharedModuleContext, type LangiumServices, type PartialLangiumServices } from 'langium/lsp';
import { createGlspModule, createGlspSharedModule } from '../../framework/langium/worker/module.js';
import {
    ActionNodeDSLGeneratedModule,
    AdmissionActionNodeDSLGeneratedModule,
    BranchNodeDSLGeneratedModule,
    HealthcareDsmlGeneratedSharedModule
} from './generated/module.js';
import { HealtcareDsmlScopeProvider, HealthcareExternalNodeInformationService } from './healthcare-dsml-references.js';
import { HealthcareDsmlValidator, registerValidationChecks } from './healthcare-dsml-validator.js';
console.log('healthcare-dsml-module.js: Module starting to load.');
/**
 * Declaration of custom services - add your own service classes here.
 */
export type HealthcareDsmlAddedServices = {
    validation: {
        HealthcareDsmlValidator: HealthcareDsmlValidator;
    };
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type HealthcareDsmlServices = LangiumServices & HealthcareDsmlAddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const HealthcareDsmlModule: Module<HealthcareDsmlServices, PartialLangiumServices & HealthcareDsmlAddedServices> = {
    validation: {
        HealthcareDsmlValidator: () => new HealthcareDsmlValidator()
    },
    references: {
        ScopeProvider: services => new HealtcareDsmlScopeProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createHealthcareDsmlServices(context: DefaultSharedModuleContext) {
    console.log('createHealthcareDsmlServices');
    const shared = inject(
        createGlspSharedModule(context, {
            ExternalNodeInformationService: services => new HealthcareExternalNodeInformationService(services)
        }),
        HealthcareDsmlGeneratedSharedModule
    );

    const BranchNodeDSL = inject(createGlspModule({ shared }), BranchNodeDSLGeneratedModule, HealthcareDsmlModule);
    const AdmissionActionNodeDSL = inject(createGlspModule({ shared }), AdmissionActionNodeDSLGeneratedModule, HealthcareDsmlModule);
    const ActionNodeDSL = inject(createGlspModule({ shared }), ActionNodeDSLGeneratedModule, HealthcareDsmlModule);

    shared.ServiceRegistry.register(BranchNodeDSL);
    shared.ServiceRegistry.register(AdmissionActionNodeDSL);
    shared.ServiceRegistry.register(ActionNodeDSL);
    // TODO Right now all languages register the same validation,
    // but it likely makes sense to seperate the validators as well
    registerValidationChecks(BranchNodeDSL);
    registerValidationChecks(AdmissionActionNodeDSL);
    registerValidationChecks(ActionNodeDSL);

    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, BranchNodeDSL, AdmissionActionNodeDSL, ActionNodeDSL };
}
